### ISSUE TITLE
Dependabot findings don't show which transitive dependencies lead to vulnerability

### ISSUE THREAD

**Issue by zabicki-iterable** [scalacenter/sbt-dependency-submission#104]
We recently started using this plugin, and it's great to have all the vulnerable dependencies in dependabot. The problem is that when it's a transitive dependency that is vulnerable, the depenedabot ticket doesn't have any information about which dependencies are causing the problem. So we have to do a lot of manual work outside of dependabot to figure out what needs to be upgraded.

It would be great if the transitive dependency chain was represented in the dependabot ticket so we could just look at that and know what to upgrade.

**Comment by adpi2** [comment]
The security report are computed by Github based on the graph that we send, which contains all the information about transitive dependencies. So there is nothing we can do on our end to fix this issue. I invite you to open a discussion in [Github community](https://github.com/orgs/community/discussions).

**Comment by zabicki-iterable** [comment]
Thank you for the clarification!
