### ISSUE TITLE
Sbt Dependency Submission reports wrong scala-library

### ISSUE THREAD

**Issue by erikvanoosten** [scalacenter/sbt-dependency-submission#106]
https://github.com/erikvanoosten/metrics-scala/network/dependencies shows:

<img width="549" alt="org.scala-lang:scala-library 2.13.8 Detected by sbt-github-dependency-submission on May 29, 2023 (unknown) · build.sbt" src="https://github.com/scalacenter/sbt-dependency-submission/assets/630600/44600ef1-e31f-4751-8c93-332324924900">

while 2.13.8 is not used in this project. Only scala versions 3.1.3, 2.13.10, 2.12.17 and 2.11.12 are used.

**Comment by adpi2** [comment]
The `scala3-library:3.1.3` depends on the `scala-library:2.13.8`:

https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.1.3/scala3-library_3-3.1.3.pom
