### ISSUE TITLE
Fill in the `unknown` in the Dependency Graph

### ISSUE THREAD

**Issue by adpi2** [scalacenter/sbt-dependency-submission#111]
Find out what is the missing piece of information we could provide instead of `unknown`.

![image](https://github.com/scalacenter/sbt-dependency-submission/assets/13123162/e5f6b04f-9b24-49ee-af96-34161234a24c)

**Comment by laughedelic** [comment]
I think it's supposed to be the "ecosystem", i.e. in this case `Maven`. 

Here is how this looks in some other view. This has been submitted with this plugin, so the information should be there, but I don't know if it could be still missing in some specific field:
![Screen Shot 2023-06-27 at 16 36 38](https://github.com/scalacenter/sbt-dependency-submission/assets/766656/f1e8ea61-ba1c-4eb8-b03d-f780ed52f7a0)

Also, for the automatically detected dependencies it has `GitHub Actions` or `pip` between those parentheses.

**Comment by aegilops** [comment]
I read this and went to fix it, only to find that it's already been fixed! 🥳 

See https://github.com/scalacenter/sbt-dependency-submission/blob/main/sbt-plugin/src/main/scala/ch/epfl/scala/GithubDependencyGraphPlugin.scala#L204

The string used in the PURL is now `maven`, which Dependency Graph and Dependabot both support.

I would recommend confirming this and then closing this issue.

**Comment by laughedelic** [comment]
I can confirm that it's resolved: 

![Screen Shot 2023-10-30 at 19 25 25](https://github.com/scalacenter/sbt-dependency-submission/assets/766656/ea241bc1-ac34-4296-8bdf-bfbf49089484)
