### ISSUE TITLE
Generating report locally

### ISSUE THREAD

**Issue by laughedelic** [scalacenter/sbt-dependency-submission#112]
Is it possible to run the sbt plugin locally to generate the report (that gets submitted to GitHub) or any intermediate information dump to be able to inspect it manually or potentially pass to other tools?

**Comment by laughedelic** [comment]
I noticed this line in the logs:

```
[info] Submitted successfully as https://api.github.com/repos/<org>/<repo>/dependency-graph/snapshots/1234321
```

And I tried getting that snapshot via API:

```shell
gh api 'repos/<org>/<repo>/dependency-graph/snapshots/1234321'
```

The json I got is exactly the report I mentioned above. So the feature request is
- simplify sbt plugin usage, so that it's possible to run it and get this report locally (not in GHA CI)
- maybe (optionally?) upload this file as an artifact in GitHub Actions, so that it's easier to inspect without using API
- or maybe output it as a [job summary](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/)

**Comment by adpi2** [comment]
Thanks, these are valid feature requests. I don't have time to work on them though. Feel free to contribute.

**Comment by adpi2** [comment]
It is now possible to run `githubGenerateSnapshot` to generate a snapshot locally:
```
sbt:scaladex> githubGenerateSnapshot
[info] Resolving snapshot of build.sbt
[info] Setting Scala version to 2.13.10 on 8 projects.
[info] Reapplying settings...
[info] set current project to scaladex (in build file:/home/piquerez/github/scalacenter/scaladex/)
[info] Including dependency graph of server_2.13
[info] Including dependency graph of scaladex_2.13
[info] Including dependency graph of data_2.13
[info] Including dependency graph of webclient_sjs1_2.13
[info] Including dependency graph of infra_2.13
[info] Including dependency graph of core_sjs1_2.13
[info] Including dependency graph of core_2.13
[info] Including dependency graph of template_2.13
[success] Total time: 3 s, completed May 15, 2024, 9:51:42 AM
[info] Dependency snapshot written to /tmp/dependency-snapshot-3080240838874963577.json
```

If executed locally, the snapshot contains an empty string anywhere a Github id is expected.

In a Github CI, the snapshot file is declared as an action output.
