### ISSUE TITLE
the Scala compiler itself is not included in dependencies

### ISSUE THREAD

**Issue by armanbilge** [scalacenter/sbt-dependency-submission#117]
Even though it's not a runtime dependency for most projects, the compiler itself is an important dependency that emits compiled code.

I did a quick look and couldn't find any historical CVEs that fell into this case, but ... if there was a CVE where the compiler emitted vulnerable code, I expect this would be reported as a vulnerability on the `scala-compiler` artifact specifically (i.e. not a runtime dependency like `scala-library`). So it seems like the compiler should be included in the list of dependencies.

NB if a project is using compiler plugins like kind-projector or better-monad-for in Scala 2 or Scala Native in Scala 3, then the Scala compiler _does_ appear in the submitted dependencies as a transitive of the plugin.

**Comment by adpi2** [comment]
I think it does: https://github.com/scalacenter/sbt-dependency-submission/network/dependencies?q=scala-compiler

Or do you have a repo where it should appear but does not?
