### ISSUE TITLE
Excluding internal Nexus dependencies is not working

### ISSUE THREAD

**Issue by andreostermeier27** [scalacenter/sbt-dependency-submission#150]
Hey there,

I have just added your GitHub action to one of our Scala repositories, which also (as most of the others) has dependencies to libraries stored in our internal Nexus.

[warn] 		io.<company>:cloud-scalalib-sbt:0.23.2 (sbtVersion=1.0, scalaVersion=2.12)
...
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading io.<company>:cloud-scalalib-sbt;sbtVersion=1.0;scalaVersion=2.12:0.23.2
...
[error]   forbidden: https://nexus.<path>.<company>.io/repository/<company>-releases/io.<company>/cloud-scalalib-sbt/scala_2.12/sbt_1.0/0.23.2/ivys/ivy.xml
....

I have tried all kind of possibilities to exclude this library just to get to any result before troubleshooting, but it always results in the exact same error log.

Any idea how to overcome this? Is there a proposal how this action could interact with our internal Nexus in a secure manner?

Thanks for your feedback and thanks for all the effort you have been putting into the code behind this action,
Andre

**Comment by adpi2** [comment]
> Any idea how to overcome this? Is there a proposal how this action could interact with our internal Nexus in a secure manner?

In the `build.sbt`, I would try something like:

```scala
excludeDependencies ++= {
  if (isGithubCI) // if the CI env var is set
    Seq(ExclusionRule("io", "cloud-scalalib-sbt"))
  else Seq.empty
}
```
