### ISSUE TITLE
sbt-dependency-submission@v3 does not use v3 version of sbt plugin

### ISSUE THREAD

**Issue by brunoballekens** [scalacenter/sbt-dependency-submission#185]
Just bumped the action from sbt-dependency-submission@v2 to sbt-dependency-submission@v3

Build fails:
![image](https://github.com/scalacenter/sbt-dependency-submission/assets/30588687/3e77fad7-0a81-4e56-8885-c74128542c2d)

![image](https://github.com/scalacenter/sbt-dependency-submission/assets/30588687/8eb79d11-fe0a-4f57-8b67-bae86731640a)

Workaround: specify 3.0.0 plug in  the workflow file:
```
- uses: scalacenter/sbt-dependency-submission@v3
  with:
    sbt-plugin-version: "3.0.0"
```

**Comment by adpi2** [comment]
Thanks for reporting this.

**Comment by adpi2** [comment]
Fixed by #186

**Comment by brunoballekens** [comment]
Thanks for the fast turnaround 👍 

I guess i have to wait until the 3.0.1 plugin is available on maven central ?

**Comment by adpi2** [comment]
> I guess i have to wait until the 3.0.1 plugin is available on maven central ?

Yes, it is released but it will take a bit of time to be available on Maven Central.

**Comment by brunoballekens** [comment]
It's available and works as a charm! Thank you
