### ISSUE TITLE
Should we rename this action `scala-dependency-submission`

### ISSUE THREAD

**Issue by adpi2** [scalacenter/sbt-dependency-submission#40]
It seems the pattern `*-dependency-submission` is more common for such Github actions that push dependency snapshot to the Github Dependency Submission API:
- https://github.com/actions/go-dependency-submission
- https://github.com/mikepenz/gradle-dependency-submission
- https://github.com/marketplace/actions/elm-dependency-submission
- https://github.com/marketplace/actions/sbom-submission-action

@ckipp01 @julienrf @sjrd any opinion on this?

**Comment by sjrd** [comment]
Probably `sbt-dependency-submission`, no?

**Comment by julienrf** [comment]
“dependency-submission” is not very explicit to me, but if that’s the de facto standard, let’s use that!

**Comment by kubukoz** [comment]
@adpi2 @julienrf maybe `scala-github-dependency-submission`? The format is specific to github, right?

Also flagging for scala-cli folks - cc @romanowski @alexarchambault

**Comment by adpi2** [comment]
Thanks @kubukoz for the suggestion. We also thought of `sbt-dependency-submission-action`, to state clearly that this is a Github action.

But `***-dependency-submission` has become a standard in other ecosystems ([go](https://github.com/actions/go-dependency-submission
), [gradle](https://github.com/mikepenz/gradle-dependency-submission), [elm](https://github.com/marketplace/actions/elm-dependency-submission), [sbom](https://github.com/marketplace/actions/sbom-submission-action)). So I will stick to it. That's not really self-explanatory but a quick look at the Readme should cFor those who don't know, larify that this is a Github action and nothing more.

> Also flagging for scala-cli folks - cc @romanowski @alexarchambault

Here is [another thread](https://github.com/scalacenter/sbt-dependency-submission/issues/37) where we discuss the possibility of a build-tool agnostic version of this action using BSP. It is not yet possible to extract a dependency graph using BSP but we could add this feature. It's not a niche feature, as it could be reused in many languages, not only scala, and in other BSP servers: would be cool to view the dependency graph in Metals for instance.
